### ISSUE TITLE
Error - Importing Filter

### ISSUE THREAD

**Issue by aerosdan** [Axway-API-Management-Plus/Policy-Loop-custom-filter#2]
When trying to "Import Custom Filter" named "CircuitLoopFilterDesc.xml" the follow error pops.

![ERRO1](https://user-images.githubusercontent.com/50891053/58481659-34c2af00-8133-11e9-8ee6-07f639cb7608.JPG)

**Comment by cwiechmann** [comment]
Can you please let us know, which API-Gateway version including the Service-Pack level you are using?

**Comment by aerosdan** [comment]
> Can you please let us know, which API-Gateway version including the Service-Pack level you are using?

V.7.4.1
The Service Pack you asking for its like the module? If so I`m using Policy Studio

It was brought to my attention that this particular file is not required to import the filter. I successfully had imported the other one (CircuitLoopTypeSet.xml) with no error and the filter `circuit loop` had appeared.

**Comment by cwiechmann** [comment]
Okay, thanks for providing feedback. I'll close this issue for now. Please let use know, if you run into further issues with that.

And BTW: You should update your platform, as 7.4.1 is really very old. It has been released in 2015 and became End of support in April 2018.

**Comment by aerosdan** [comment]
But, is it correct the way I did? Not importing the "CircuitLoopFilterDesc.xml"?

**Comment by cwiechmann** [comment]
Not exactly sure, why do you have got this error, but as long as you see the new filter, you should be okay. 
Please see here for more details about creating & registering Custom-Filters. Maybe it's matter of doing this in the right order:
https://docs.axway.com/bundle/APIGateway_77_DeveloperGuide_allOS_en_HTML5/page/Content/DeveloperGuideTopics/custom_filter_extension_kit.htm

**Comment by aerosdan** [comment]
Thanks for your attention and help.
